# Generated by Django 5.0.6 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageorig',
            field=models.ImageField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
