# Generated by Django 5.0.6 on 2024-07-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_imageorig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_product', models.CharField(max_length=255)),
                ('old_code', models.CharField(max_length=100)),
                ('old_ean', models.CharField(max_length=13)),
                ('old_image', models.ImageField(upload_to='product_updates/')),
                ('new_product', models.CharField(blank=True, max_length=255, null=True)),
                ('new_code', models.CharField(blank=True, max_length=100, null=True)),
                ('new_ean', models.CharField(blank=True, max_length=13, null=True)),
                ('new_image', models.ImageField(blank=True, null=True, upload_to='product_updates/')),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductChange',
        ),
    ]
