# Generated by Django 5.0.6 on 2024-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productupdate_delete_productchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productupdate',
            name='old_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productupdate',
            name='old_ean',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='productupdate',
            name='old_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
