# Generated by Django 5.0.6 on 2024-07-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productupdate_old_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productupdate',
            name='old_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_updates/'),
        ),
    ]
